<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>md2pdf</AssemblyName>
    <RootNamespace>Md2Pdf</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets/report.css" />
  </ItemGroup>

</Project>
